Promise.resolve(3).then((result) => console.log(result));

Promise.reject("error").catch((error) => console.log(error));